runtime: custom
env: flex
entrypoint: gunicorn -b :$PORT fingerprint_api:app

runtime_config:
  python_version: 2

service: smiles-to-fingerprint

resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 5
  cool_down_period_sec: 60 # default value
  cpu_utilization:
    target_utilization: 0.9

threadsafe: true
#
#health_check:
#  enable_health_check: True
